### ISSUE TITLE
code release time

### ISSUE THREAD

**Issue by chuxiang93** [HiLab-git/SCPM-Net#1]
I am very interested in your paper published in MICCAI 2020. When will you open the code?

Thanks,

**Comment by Luoxd1996** [comment]
Hi,mjq93;
I am not sure, if we submit the manuscript to a journal, we will release it as soon as possible (recently my supervisor is revising the manuscript, maybe needs one month or more).
Best;
Xiangde.

**Comment by chuxiang93** [comment]
> Hi,mjq93;
> I am not sure, if we submit the manuscript to a journal, we will release it as soon as possible (recently my supervisor is revising the manuscript, maybe needs one month or more).
> Best;
> Xiangde.

Hello, Xiangde:
       Five months have passed, do you still plan to open the source code? (Recently, I have encountered a bottleneck in the lung nodule detection task. I hope I can learn from the relevant ideas in this paper.)
Thanks,

**Comment by Luoxd1996** [comment]
Hi, mjq93, 
Sorry, there is too much work that needs to do in the past half-year, so the release date of the code was delayed. Now, I am working hard to finish this extension maybe it also needs several months, and I suggest you reimplement CPMNet by yourself, if you have any questions, please email me (luoxd1996@gmail.com).
Best,
Xiangde.

**Comment by JXQI** [comment]
> Hi, mjq93,
> Sorry, there is too much work that needs to do in the past half-year, so the release date of the code was delayed. Now, I am working hard to finish this extension maybe it also needs several months, and I suggest you reimplement CPMNet by yourself, if you have any questions, please email me ([luoxd1996@gmail.com](mailto:luoxd1996@gmail.com)).
> Best,
> Xiangde.
Do you plan to open the source code soon? thanks

**Comment by Luoxd1996** [comment]
The network and loss function is  available.
