### ISSUE TITLE
code

### ISSUE THREAD

**Issue by 1419786491** [HiLab-git/SCPM-Net#2]
大神你好可以开源你的全部代码吗

**Comment by Luoxd1996** [comment]
Hi,
Due to the privacy concerns, as this work supported by a company, we just can release the code of the proposed network and loss function. I am so sorry.
Best,
Xiangde.

**Comment by 1419786491** [comment]
好的 依然多谢你哈

**Comment by Luoxd1996** [comment]
Hi,
You are welcome, good luck with your research.
Best,
Xiangde.
