### ISSUE TITLE
questions about dataset

### ISSUE THREAD

**Issue by oliva-cool** [HiLab-git/SCPM-Net#3]
Hi，
       Thanks for your awesome work. I am confused about the ground truth.Could you tell me  how to sample one patch from the luna16 dataset, and map the ground truth of one patch with the nodule location and size annotation, which contain one more nodule?

**Comment by Luoxd1996** [comment]
Hi, LuckyBrighter, 
It's a very fundamental and important problem. Maybe you can read the reference paper DeepLung(https://arxiv.org/abs/1801.09555), or the latest work nnDetection (https://github.com/MIC-DKFZ/nnDetection).
Best,
Xiangde.

**Comment by oliva-cool** [comment]
Thanks so much for your reply, I will read them!
