### ISSUE TITLE
Output shape

### ISSUE THREAD

**Issue by Siji-chl** [HiLab-git/SCPM-Net#6]
Hi，
Thanks for your awesome work. I am confused about the shape of output. The shape of input is (96, 96, 96), but that of the output is (48, 48, 48) in _SCPMNet.py._ The shapes of input and output should be the same?

**Comment by Luoxd1996** [comment]
Hi, 
Maybe you can check our paper carefully, we discussed this issue in our paper.
Best,
Xiangde.
