### ISSUE TITLE
Code issues

### ISSUE THREAD

**Issue by WeebOwO** [HiLab-git/SCPM-Net#7]
Hi👋,  I am very interested in your work！I would like to ask if it is possible to release the whole training code publicly. If there is no hope for the release of the entire code, can I ask for a private copy of the code and study it.
Looking forward to your prompt reply!😊

**Comment by kacel33** [comment]
Did you get copy of the code?

**Comment by WeebOwO** [comment]
> Did you get copy of the code?

No sir, I give up in getting source code.
