### ISSUE TITLE
Can I get the copy code??

### ISSUE THREAD

**Issue by kacel33** [HiLab-git/SCPM-Net#9]
I am very interest in nodule detection in CT. 
Thanks for this work.
I would like to ask if it is possible to release the whole training code publicly.
If there is no hope for the release of the entire code, can I ask for a private copy of the code and study it.
I hope to reply. Thank you

**Comment by Luoxd1996** [comment]
Hi,
Thanks for your attention, the training code please check this project:https://github.com/zunzhumu/CPMNetv2.
Best,
Xiangde Luo.
